---
- name: ensure Podman is at the latest version
  apt:
    name: podman
  become: true

- name: ensure Podman is at the latest version
  apt:
    name: cockpit-podman
  become: true
  
- name: add container registries
  blockinfile:
    path: /etc/containers/registries.conf
    block: |
      [registries.search]
      registries = ['container-registry.oracle.com', 'quay.io', 'docker.io']
  become: true
